Add April planning session notes
tomeshnet/documents pull request #72
Opened 2017-04-27 12:53 UTC by dcwalk

2017-04-27 14:32 UTC, benhylau commented on governance/coordination-structure.md
> +| **node.tech** (_ongoing_) | benhylau |
udit

2017-04-29 00:03 UTC, dasanchez commented on governance/coordination-structure.md
> +Excerpted from [Planning Meeting Notes - November 12, 2016](https://github.com/tomeshnet/documents/blob/master/meeting_notes/20161112_planning-meeting-notes.md)
Should L27 and L28 list the April date & meeting notes?

2017-04-29 00:05 UTC, dasanchez requested changes
Cycle IV working groups were established in April

2017-05-01 23:42 UTC, benhylau commented on meeting_notes/20170424_planning-meeting-notes.md
> +	- hello@tomesh.net
Indent

2017-05-02 00:30 UTC, dcwalk commented
Fixed, thanks for the catch!

2017-05-02 00:30 UTC, merged